global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "origin"
    static_configs:
      - targets: ["origin:8000"]
  - job_name: "client"
    static_configs:
      - targets: ["client:8080"]
  - job_name: "proxy"
    static_configs:
      - targets: ["proxy:7000"]
