{
 "title": "Demo 🔥🔥🔥",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "User Experience", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% of client OK pings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100* sum(rate(\n            http_client_requests_total{target=\"ping\",code!~\"5.*\"}[1m]\n          )) /\n          sum(rate(\n            http_client_requests_total{target=\"ping\"}[1m]\n          ))"
    }
   ]
  },
  {
   "title": "Client request latency per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_client_request_duration_seconds_bucket{target=\"ping\"}[1m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_client_request_duration_seconds_bucket{target=\"ping\"}[1m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Client requests per second by code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(http_client_requests_total{target=\"ping\"}[1m]))"
    }
   ]
  },
  { "title": "State per Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "% of server OK pings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100* sum(rate(\n            http_requests_total{handler=\"/ping\",code!~\"5..\"}[1m]\n          )) /\n          sum(rate(\n            http_requests_total{handler=\"/ping\"}[1m]\n          ))"
    }
   ]
  },
  {
   "title": "Ping Server Latency Heatmap (warmer -> more)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{handler=\"/ping\", le!~\".Inf|120.0|90.0|720.0|360.0|240.0|60.0\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error requests per second by (code, version)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum by(code, pod) (rate(http_requests_total{handler=\"/ping\", code=~\"5..\", pod=~\"app.*\"}[1m])) * on(pod) group_left(version) app_build_info) by(code, version)"
    }
   ]
  },
  {
   "title": "Rollout State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Argo Rollout Rollouts in Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rollout_phase{phase=\"Progressing\"}) by(name, phase)",
     "legendFormat": "{{name}} {{phase}}"
    }
   ]
  },
  {
   "title": "Rolled Replicas per Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_build_info{pod=~\"app.*\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Argo Rollout AnalysisRun Errored/Failed Phases per Metric",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(analysis_run_metric_phase{phase=~\"Error|Failed|Running\"}) by(phase, metric)"
    }
   ]
  }
 ]
}